# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  web_client:
    build:
      context: services/web_client
    ports:
      - "9000:9000"
    networks:
      - main
    volumes:
      - "./services/web_client/src/:/app/src"
  commands_processor:
    depends_on:
      - zookeeper
      - kafka
    build:
      context: services/commands_processor
    ports:
      - "9001:9001"
    networks:
      - main
    volumes:
      - "./services/commands_processor/src/:/app/src"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    networks:
      main:
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      main:
networks:
  main:
      